# Generated by Django 5.1.7 on 2025-04-01 16:50

import django.contrib.auth.models
from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffAndSuperuser',
            fields=[
            ],
            options={
                'verbose_name': 'Staff/Superuser',
                'verbose_name_plural': 'Staff/Superusers',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
