# Generated by Django 5.1.7 on 2025-03-26 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_transaction_transaction_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='month',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='year',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True),
        ),
    ]
