# Generated by Django 5.1.7 on 2025-03-26 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_transaction_month_transaction_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='month',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='year',
        ),
    ]
