# Generated by Django 5.1.7 on 2025-04-02 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0016_officeitem_borrowmanagement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowmanagement',
            name='return_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
