# Generated by Django 5.1.7 on 2025-04-01 05:22

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('writer', models.CharField(blank=True, max_length=255, null=True)),
                ('publication', models.CharField(blank=True, max_length=255, null=True)),
                ('quantity', models.PositiveIntegerField(blank=True, default=1, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LibraryRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shelf_no', models.CharField(blank=True, max_length=10, null=True)),
                ('row_no', models.CharField(blank=True, max_length=10, null=True)),
                ('issue_date', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
                ('returned_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(blank=True, choices=[('Not Returned', 'Not Returned'), ('Returned', 'Returned'), ('Returned Date Expired', 'Returned Date Expired')], default='Not Returned', max_length=25, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('borrow_id', models.CharField(blank=True, editable=False, max_length=12, null=True, unique=True)),
                ('book', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='jisc_library.book')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_records', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='borrower', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
