# Generated by Django 5.1.7 on 2025-04-01 08:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jisc_library', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libraryrecord',
            name='issue_date',
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
    ]
