# Generated by Django 5.0.6 on 2025-04-01 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jisc_library', '0003_alter_libraryrecord_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libraryrecord',
            name='status',
            field=models.CharField(blank=True, choices=[('Not Returned', 'Not Returned'), ('Returned', 'Returned')], default='Not Returned', max_length=25, null=True),
        ),
    ]
